//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookitAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FoodLabel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_FoodLabel()
        {
            this.TBL_LabelsForRecp = new HashSet<TBL_LabelsForRecp>();
        }
    
        public int Id_FoodLabel { get; set; }
        public string Name_FoodLabel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LabelsForRecp> TBL_LabelsForRecp { get; set; }
    }
}
