//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookitDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Profile()
        {
            this.TBL_Followers = new HashSet<TBL_Followers>();
        }
    
        public int Id_Prof { get; set; }
        public int Id_User { get; set; }
        public string Name_Prof { get; set; }
        public string ProfDescription { get; set; }
        public bool ProfStatus { get; set; }
        public int Id_City { get; set; }
        public int Id_Region { get; set; }
        public string Image_Path { get; set; }
        public string Image_Name { get; set; }
    
        public virtual TBL_City TBL_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Followers> TBL_Followers { get; set; }
        public virtual TBL_Region TBL_Region { get; set; }
        public virtual TBL_User TBL_User { get; set; }
    }
}
