//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookitDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WorkshopParticipents
    {
        public int Id_Workshop { get; set; }
        public string User_Email { get; set; }
        public Nullable<bool> StatusRegistration { get; set; }
    
        public virtual TBL_User TBL_User { get; set; }
        public virtual TBL_Workshop TBL_Workshop { get; set; }
    }
}
