//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookitLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_StarsForRecp
    {
        public int Id_Recp { get; set; }
        public System.DateTime StarYear { get; set; }
        public int Id_Star { get; set; }
    
        public virtual TBL_Recipe TBL_Recipe { get; set; }
        public virtual TBL_Star TBL_Star { get; set; }
    }
}
